// binary-distribution acceptance: cargo-dist release matrix, installer
// checksum-verify install with no JS runtime on PATH, and the install one-liner
// recorded where a missing binary surfaces (README + begin skill).
//
// Criterion 2 has no live GitHub Release and no docker here — the honest local
// equivalent is: build real host artifacts with cargo-dist, serve them over
// HTTP, run the generated shell installer with THE_LOOP_DOWNLOAD_URL pointed
// at that server, on a PATH that excludes every JS runtime directory, then
// assert `the-loop --version` and that a corrupted archive fails checksum
// verification before use.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { test } from 'node:test';

import {
  assertInstallerAndChecksumArtifacts,
  assertTargetArchivesCovered,
  collectPlanArtifacts,
  COMPILED_BLOB_EXTS,
  copyFiles,
  distAvailable,
  embeddedArchiveChecksum,
  hostTriple,
  INSTALL_ONE_LINER,
  pathWithoutJsRuntimes,
  planJson,
  ROOT,
  run,
  serveDirectory,
} from './binary-distribution-helpers.js';

// ── criterion 1: cargo-dist plan publishes five targets + installers + sha256;
// no compiled artifact committed ─────────────────────────────────────────────
test('criterion 1: cargo-dist plan covers five targets, both installers, and sha256 checksums', () => {
  const plan = planJson();
  const { artifactNames, checksumArtifacts } = collectPlanArtifacts(plan);

  assertTargetArchivesCovered(artifactNames);
  assertInstallerAndChecksumArtifacts(artifactNames, checksumArtifacts);

  // Config is committed; Windows is plan-accepted (CI-built only — no local Windows).
  assert.ok(existsSync(path.join(ROOT, 'dist-workspace.toml')), 'dist-workspace.toml must be committed');
  assert.ok(
    existsSync(path.join(ROOT, '.github/workflows/release.yml')),
    'cargo-dist-generated release workflow must be committed',
  );

  // Generated workflow must still match `dist generate` output.
  const check = run('cargo', ['dist', 'generate', '--check']);
  assert.equal(
    check.status,
    0,
    `cargo dist generate --check failed (workflow drifted from generator):\n${check.stderr}\n${check.stdout}`,
  );

  // Release workflow is tag-triggered (cargo-dist-generated content).
  const workflow = readFileSync(path.join(ROOT, '.github/workflows/release.yml'), 'utf8');
  assert.match(workflow, /autogenerated by dist/, 'release.yml must be cargo-dist generated');
  assert.match(workflow, /tags:/, 'release workflow must trigger on tags');
});

test('criterion 1: no compiled release artifact is committed to the git tree', () => {
  const listed = run('git', ['ls-files', '-z']);
  assert.equal(listed.status, 0, `git ls-files failed: ${listed.stderr}`);
  const files = listed.stdout.split('\0').filter(Boolean);

  const offenders = [];
  for (const file of files) {
    const base = path.basename(file);
    const ext = path.extname(base).toLowerCase();
    // cargo-dist config and the generated installer *sources* are not committed
    // artifacts; compiled archives / binaries are the forbidden set.
    if (COMPILED_BLOB_EXTS.has(ext)) {
      offenders.push(file);
      continue;
    }
    // Bare binary names that would only appear as built products.
    if (
      base === 'the-loop'
      || base === 'the-loop.exe'
      || /^the-loop-.*\.(tar\.xz|zip|tar\.gz)$/.test(base)
    ) {
      offenders.push(file);
    }
  }

  assert.deepEqual(
    offenders,
    [],
    `compiled artifacts must not be tracked; found: ${offenders.join(', ')}`,
  );

  // target/ is gitignored so local dist builds cannot be committed by accident.
  const ignored = run('git', ['check-ignore', '-v', 'target/distrib/the-loop-installer.sh']);
  assert.equal(
    ignored.status,
    0,
    'target/distrib output must be gitignored (no accidental commit of build products)',
  );
});

/**
 * Negative path for criterion 2: serve a corrupted host archive and assert the
 * installer fails checksum verification without leaving a usable binary.
 * @param {{ distrib: string, archiveName: string, safePath: string }} opts
 */
function assertCorruptArchiveRejected(opts) {
  const { distrib, archiveName, safePath } = opts;
  const corruptDir = mkdtempSync(path.join(tmpdir(), 'the-loop-corrupt-'));
  const corruptRoot = mkdtempSync(path.join(tmpdir(), 'the-loop-install-bad-'));
  let corruptServer;
  try {
    copyFiles(distrib, corruptDir);
    // Overwrite the archive with different bytes; leave installer checksum unchanged.
    writeFileSync(path.join(corruptDir, archiveName), Buffer.from('not-a-real-archive-payload'));

    corruptServer = serveDirectory(corruptDir);
    const bad = spawnSync('sh', [path.join(corruptDir, 'the-loop-installer.sh')], {
      encoding: 'utf8',
      env: {
        ...process.env,
        PATH: safePath,
        THE_LOOP_DOWNLOAD_URL: corruptServer.baseUrl,
        THE_LOOP_INSTALL_DIR: corruptRoot,
        THE_LOOP_NO_MODIFY_PATH: '1',
        HOME: corruptRoot,
      },
      timeout: 60_000,
    });
    assert.notEqual(
      bad.status,
      0,
      'installer must refuse a checksum-mismatched archive',
    );
    const combined = `${bad.stdout}\n${bad.stderr}`;
    assert.match(
      combined,
      /checksum|want:|got:/i,
      `corrupted install must report checksum failure; got: ${combined}`,
    );
    assert.ok(
      !existsSync(path.join(corruptRoot, 'bin', 'the-loop')),
      'checksum failure must not leave a usable binary installed',
    );
  } finally {
    corruptServer?.close();
    rmSync(corruptRoot, { recursive: true, force: true });
    rmSync(corruptDir, { recursive: true, force: true });
  }
}

// ── criterion 2: shell installer + checksum verify + no JS runtime ──────────
test('criterion 2: shell installer places the-loop on PATH with checksum verification and no JS runtime', () => {
  assert.ok(distAvailable(), 'cargo-dist (`dist`) must be on PATH for these tests');

  // Real host artifacts — not config-string assertions.
  const build = run('cargo', ['dist', 'build'], { timeout: 300_000 });
  assert.equal(
    build.status,
    0,
    `cargo dist build failed:\nstdout: ${build.stdout}\nstderr: ${build.stderr}`,
  );

  const distrib = path.join(ROOT, 'target/distrib');
  const installer = path.join(distrib, 'the-loop-installer.sh');
  assert.ok(existsSync(installer), 'host build must produce the-loop-installer.sh');

  const triple = hostTriple();
  const archiveName = `the-loop-${triple}.tar.xz`;
  const archivePath = path.join(distrib, archiveName);
  assert.ok(
    existsSync(archivePath),
    `host build must produce ${archiveName} for local install exercise`,
  );

  const installerText = readFileSync(installer, 'utf8');
  // cargo-dist must embed a sha256 for the host archive (checksum is the point).
  assert.match(
    installerText,
    /_checksum_style="sha256"/,
    'installer must embed sha256 checksum verification for the built archive',
  );
  const embeddedChecksum = embeddedArchiveChecksum(installerText, archiveName);

  // Confirm embedded checksum matches the real archive bytes.
  const actual = spawnSync('shasum', ['-a', '256', archivePath], { encoding: 'utf8' });
  assert.equal(actual.status, 0, `shasum failed: ${actual.stderr}`);
  const actualChecksum = actual.stdout.trim().split(/\s+/, 2)[0];
  assert.equal(
    embeddedChecksum,
    actualChecksum,
    'installer-embedded checksum must match the built archive',
  );

  const safePath = pathWithoutJsRuntimes();
  const server = serveDirectory(distrib);
  const installRoot = mkdtempSync(path.join(tmpdir(), 'the-loop-install-'));

  try {
    // Happy path: fetch → checksum-verify → install → --version.
    const install = spawnSync('sh', [installer], {
      encoding: 'utf8',
      env: {
        ...process.env,
        PATH: safePath,
        THE_LOOP_DOWNLOAD_URL: server.baseUrl,
        THE_LOOP_INSTALL_DIR: installRoot,
        THE_LOOP_NO_MODIFY_PATH: '1',
        // Isolate HOME so receipt writes stay under the temp root.
        HOME: installRoot,
      },
      timeout: 60_000,
    });
    assert.equal(
      install.status,
      0,
      `installer failed:\nstdout: ${install.stdout}\nstderr: ${install.stderr}`,
    );
    assert.match(
      `${install.stdout}${install.stderr}`,
      /everything's installed|installing to/i,
      'installer should report a successful install',
    );

    const binPath = path.join(installRoot, 'bin', 'the-loop');
    assert.ok(existsSync(binPath), `installer must place the-loop at ${binPath}`);

    const version = spawnSync(binPath, ['--version'], {
      encoding: 'utf8',
      env: {
        ...process.env,
        PATH: `${path.join(installRoot, 'bin')}${path.delimiter}${safePath}`,
      },
    });
    assert.equal(
      version.status,
      0,
      `the-loop --version failed:\nstdout: ${version.stdout}\nstderr: ${version.stderr}`,
    );
    assert.match(
      version.stdout,
      /the-loop\s+\d+\.\d+\.\d+/,
      `unexpected --version output: ${version.stdout}`,
    );

    assertCorruptArchiveRejected({ distrib, archiveName, safePath });
  } finally {
    server.close();
    rmSync(installRoot, { recursive: true, force: true });
  }
});

// ── criterion 3: install one-liner recorded at missing-binary surfaces ──────
test('criterion 3: README install section and begin skill carry the install one-liner', () => {
  const readme = readFileSync(path.join(ROOT, 'README.md'), 'utf8');
  assert.match(
    readme,
    /## Install\b/,
    'README must have an Install section',
  );
  assert.ok(
    readme.includes(INSTALL_ONE_LINER),
    `README Install section must carry the exact install one-liner:\n${INSTALL_ONE_LINER}`,
  );

  const begin = readFileSync(path.join(ROOT, 'plugin/skills/begin/SKILL.md'), 'utf8');
  assert.ok(
    begin.includes(INSTALL_ONE_LINER),
    `begin skill must record the install one-liner as the missing-binary remedy:\n${INSTALL_ONE_LINER}`,
  );
  assert.match(
    begin,
    /command-not-found|missing binary|not on PATH|not found/i,
    'begin skill must name the missing-binary / command-not-found posture',
  );
  // Still the Node CLI invocation — do not change that in this task.
  assert.match(
    begin,
    /node "\$\{CLAUDE_PLUGIN_ROOT\}\/bin\/the-loop\.js"/,
    'begin skill must still invoke the Node CLI directly in this slice',
  );
});
